a=input("")
b=input("")
print(a + " " + b)
list_a=list(a)
list_b=list(b)
len_a = len(str(list_a))
len_b = len(str(list_b))
print(str(list_a) + "\n" + str(list_b))
print(len_a,len_b)
len_la = len(list(a))
len_lb = len(list(b))
print(len_la,len_lb)

#list(var) is different from str(list(var))