a=input("Enter first Text:")
b=input("Enter first Text:")
c=input("Enter first Text:")
a1="1".join(a)
print(a1)
b1=a.replace("e","!")
b2=b1.replace("a","6")
print(b2)
c1=c.split(" ")
print(c1)