print("Dash\tTeam")
print("************************")
print("Team\rDash52\rTeam3")
print("************************")
print("Learning python in\n DashTeam")
print("************************")
print('Dash\bLearning')
print("************************")
print('Dash\'Learning')
print('He isn\'t doing ok')